# Generated by Django 4.1.7 on 2023-03-16 18:00

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(help_text='Required / max-50 / letters, numbers, symbols and underscores', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Required / max-50 / letters, numbers, symbols and underscores', max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(help_text='Required / Follow email schema ex: john@doe.com', max_length=200, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], help_text="Required / User's gender", max_length=50, verbose_name='Gender')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='School')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street number')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday date')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='Profile picture')),
                ('joining_date', models.DateTimeField(auto_now_add=True, verbose_name='Joining date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
